### ISSUE TITLE
Request signature is invalid when changing the request url

### ISSUE THREAD

**Issue by JeroenEeuwes** [bunq/postman#5]
I can run the "get events" request and then I get a number of events. The last entry in the response is the Pagination. It looks like this (I edited the real values):

"Pagination": {
        "future_url": "/v1/user/12345/event?newer_id=6789012345",
        "newer_url": null,
        "older_url": "/v1/user/12345/event?older_id=4567890123"
    }

When I modify the get request url to 

{{host}}/v1/user/{{user_id}}/event?newer_id=6789012345

the request wwill return an error: 

{
    "Error": [
        {
            "error_description": "The request signature is invalid.",
            "error_description_translated": "The request signature is invalid."
        }
    ]
}

Anything added to the url gives the same error. So if I change the original request to 

{{host}}/v1/user/{{user_id}}/event?count=200

the same error occurs. 

So how am I supposed to get more events?

**Comment by kojoru** [comment]
Yep, there's a bug in the signing code that doesn't take the query params into account. I'll need to fix that or you can submit a PR in the meantime if you feel like it.

**Comment by JeroenEeuwes** [comment]
If I would know anything about programming in Postman I might, but since I do not I'd rather leave this to the professionals :)

**Comment by kojoru** [comment]
@JeroenEeuwes please check if the version from the pull request works for you

**Comment by JeroenEeuwes** [comment]
Thanks, this works great! I tried with url's like this

{{host}}/v1/user/{{user_id}}/event?count=1 

or

{{host}}/v1/user/{{user_id}}/event?count=1&older_id=123456789

I'm assuming it will keep working regardless of the number of parameters :)

**Comment by kojoru** [comment]
Amazing! We've merged that fix into the master branch.
